---
# tasks file for roles/conf_services

# 1. Deshabilitar servicios innecesarios
- name: Deshabilitar y detener servicios innecesarios (postfix)
  ansible.builtin.systemd:
    name: postfix
    enabled: false
    state: stopped

# 2. Configuración de Firewall
- name: Configuracion de Firewall
  block:
    # Firewalld para RHEL/CentOS
    - name: Habilitar firewalld en RHEL/CentOS
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
      when: ansible_facts['os_family'] == 'RedHat'

    # UFW para Ubuntu/Debian
    - name: Habilitar UFW en Ubuntu/Debian
      community.general.ufw:
        rule: allow
        name: OpenSSH
      when: ansible_facts['os_family'] == 'Debian'

    - name: Habilitar UFW de forma predeterminada
      ansible.builtin.command:
        cmd: "ufw --force enable"
      when: ansible_facts['os_family'] == 'Debian'
      changed_when: false

- name: Capturar estado del firewall
  ansible.builtin.set_fact:
    firewall_status: |
      {% if ansible_facts['os_family'] == 'RedHat' %}
      Firewalld habilitado
      {% elif ansible_facts['os_family'] == 'Debian' %}
      UFW habilitado
      {% endif %}
