---
# tasks file for roles/conf_ssh

# 3. Configuración de SSH (Cambiar puerto, deshabilitar root login)
- name: Configuracion SSH
  notify:
    - Reiniciar SSH
  block:
    - name: Configurar SSH para mayor seguridad (Default PermitRootLogin = no)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin {{ root_login | default('no') }}"

    - name: Configurar autenticación SSH (Deshabilitar contraseña) (Default PasswordAuthentication = no)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication {{ passwd_auth | default('no') }}"

    - name: Configurar puerto de SSH (Default Port = 22)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?Port"
        line: "Port {{ ssh_port | default(22) }}"
        state: present

    - name: Configurar SSH para permitir solo ciertos usuarios si se especifican
      block:
        - name: Agregar directiva AllowUsers si hay usuarios (Default AllowUsers = root ansible)
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: "^#?AllowUsers"
            line: "AllowUsers root ansible {{ allowed_ssh_users }}"
            state: present
          when: allowed_ssh_users is defined and allowed_ssh_users | length > 0

        - name: Eliminar directiva AllowUsers si no hay usuarios
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: "^#?AllowUsers"
            state: absent
          when: allowed_ssh_users is not defined or allowed_ssh_users | length == 0

    - name: Deshabilitar Autenticacion con contraseñas Vacias (Default PermitEmptyPasswords = no)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitEmptyPasswords"
        line: "PermitEmptyPasswords {{ pwd_empty | default('no') }}"
        state: present

    - name: Limitar las sesiones abiertas simultáneas de SSH (Default MaxSessions = 10)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?MaxSessions"
        line: "MaxSessions {{ max_session | default('10') }}"
        state: present

    - name: Establecer tiempo de inactividad máximo antes de desconectar sesión SSH (Default ClientAliveInterval = 300)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?ClientAliveInterval"
        line: "ClientAliveInterval {{ client_alive | default('300') }}" # 300 segundos (5 minutos)
        state: present
