---
# tasks file for roles/conf_firewall

# 4. Configuración de Firewall
- name: Configurar firewall según el sistema operativo
  block:
    # Firewalld para RHEL/CentOS
    - name: Asegurarse de que firewalld está instalado en RHEL/CentOS
      ansible.builtin.yum:
        name: firewalld
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Habilitar firewalld en RHEL/CentOS
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
      when: ansible_facts['os_family'] == 'RedHat'

    # UFW para Ubuntu/Debian
    - name: Asegurarse de que UFW está instalado en Ubuntu/Debian
      ansible.builtin.apt:
        name: ufw
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Habilitar UFW en Ubuntu/Debian
      community.general.ufw:
        rule: allow
        name: OpenSSH
      when: ansible_facts['os_family'] == 'Debian'

    - name: Habilitar UFW de forma predeterminada
      ansible.builtin.command:
        cmd: "ufw --force enable"
      when: ansible_facts['os_family'] == 'Debian'
      changed_when: false

- name: Capturar estado de instalación del firewall
  ansible.builtin.set_fact:
    firewall_installed: |
      {% if ansible_facts['os_family'] == 'RedHat' %}
      Firewalld instalado
      {% elif ansible_facts['os_family'] == 'Debian' %}
      UFW instalado
      {% endif %}
