---
# tasks file for roles/conf_param_kernel

# 5. Deshabilitar ICMP ping responses (prevención de descubrimiento de red)
- name: Deshabilitar respuesta a ping
  ansible.posix.sysctl:
    name: net.ipv4.icmp_echo_ignore_all
    value: 1 # deshabilita la respuesta a las solicitudes de ping
    state: present
    reload: true

# 10. Seguridad del Kernel
- name: Configurar parámetros de seguridad del kernel
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    sysctl_set: true
  loop:
    - { name: "net.ipv4.conf.all.accept_redirects", value: 0 } # Deshabilita la aceptación de redirecciones ICMP en el sistema
    - { name: "net.ipv4.conf.all.send_redirects", value: 0 } # Deshabilita el envío de redirecciones ICMP
    - { name: "net.ipv4.conf.all.rp_filter", value: 1 } # Habilita el filtro de suplantación de IP (Reverse Path Filtering) - spoofing
    - { name: "net.ipv4.tcp_syncookies", value: 1 } # Habilita las SYN cookies, medida de protección contra ataques SYN flood.

- name: Deshabilitar core dumps
  ansible.posix.sysctl:
    name: fs.suid_dumpable # asegurar la memoria de páginas de kernel
    value: 0
    state: present
    reload: true
