---
# tasks file for roles/conf_firewalld

- name: Configurar firewall según el sistema operativo
  block:
    # Firewalld para RHEL/CentOS
    - name: Asegurarse de que firewalld está instalado en RHEL/CentOS
      ansible.builtin.yum:
        name: firewalld
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Habilitar firewalld en RHEL/CentOS
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
      when: ansible_facts['os_family'] == 'RedHat'

    # UFW para Ubuntu/Debian
    - name: Asegurarse de que UFW está instalado en Ubuntu/Debian
      ansible.builtin.apt:
        name: ufw
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Habilitar UFW en Ubuntu/Debian
      community.general.ufw:
        rule: allow
        name: OpenSSH
      when: ansible_facts['os_family'] == 'Debian'

    - name: Habilitar UFW de forma predeterminada
      ansible.builtin.command:
        cmd: "ufw --force enable"
      when: ansible_facts['os_family'] == 'Debian'
      changed_when: false
