---
# tasks file for roles/install_pkgs

# 0. Establecer política de auditoría
- name: Instalar auditd
  block:
    - name: Instalar auditd en RHEL/CentOS
      ansible.builtin.yum:
        name: audit
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Instalar auditd en Ubuntu/Debian
      ansible.builtin.apt:
        name: auditd
        state: present
      when: ansible_facts['os_family'] == 'Debian'

- name: Capturar información de la instalación de auditd
  ansible.builtin.set_fact:
    auditd_installed: true
